n1 = int(input('Enter the number 1 : '))
n2 = int(input('Enter the number 2 : '))
n3 = int(input('Enter the number 3 : '))
n4 = int(input('Enter the number 4 : '))
print('The maximum among four is',max(n1,n2,n3,n4))